### ISSUE TITLE
Doesn't work in Sublime Text 3

### ISSUE THREAD

**Issue by paulyoung** [pheuter/BitcoinTicker#1]
``` python
ImportError: No module named 'urllib2'
```

**Comment by pheuter** [comment]
Seems like Python 3 doesn't have `urllib2`, it is merged with `urllib`

**Comment by paulyoung** [comment]
Now getting `ImportError: No module named 'urlparse'`

**Comment by paulyoung** [comment]
Now seeing `UnboundLocalError: local variable 'btc_in_usd' referenced before assignment`
